name: AI DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-scan:

    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:

      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Docker Buildx
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -f docker/Dockerfile -t secure-node-app .

      # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y

          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -

          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list

          sudo apt-get update
          sudo apt-get install trivy -y

      # Run Trivy Scan
      - name: Run Trivy Scan
        run: |
          trivy image --scanners vuln --severity HIGH,CRITICAL secure-node-app

      # Export JSON Report
      - name: Export Trivy Report
        run: |
          mkdir -p reports
          trivy image -f json -o reports/report.json secure-node-app

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install Python Dependencies
      - name: Install Python Dependencies
        run: |
          pip install requests boto3

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Run AI Recommendation Engine
      - name: Run AI Analysis
        run: |
          cd scripts
          python ai_recommendation.py

      # Send Slack Alert
      - name: Send Slack Alert
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          cd scripts
          python slack_alert.py

      # Upload Artifact
      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: reports/report.json